# Site
name: "CortexFlow Blog"
description: "CortexFlow Blog is the official blog of the CortexFlow organization. Here you will find articles and tutorial about the latest update of Cortexflow's project"
logo: "assets/images/logo.png"
favicon: "assets/images/logo.png"
url: "https://blog.cortexflow.org"
baseurl: ""
email: "lorenzotettamanti5@gmail.com"

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    lorenzo-tettamati:
      name:           Lorenzo Tettamanti
      site:           https://github.com/LorenzoTettamanti
      avatar:         "assets/images/avatar1.jpg"
      bio:            ""
      email:          lorenzotettamanti5@gmail.com
      twitter:        

    lorenzo-bradanini:
      name:           Lorenzo Bradanini
      site:           https://github.com/lorebrada
      avatar:         "assets/images/avatar2.jpg"
      bio:            ""
      email:          lorenzolollobradanini@gmail.com
      twitter:        
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Lorenzo Tettamanti
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]