name: Publish and Update Blog

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "20.15.0"

      - name: Install dependencies
        run: npm install ghost-cli@latest -g

      - name: Install node modules in current directory + security features
        run: |
          cd current 
          rm -rf node_modules package-lock.json
          npm install --force

      - name: Start ghost server
        run: ghost start --production

      - name: Install GSSG command
        run: npm install -g ghost-static-site-generator

      - name: Build site
        run: gssg build --url https://www.cortexflow.org --dest ./static --theme liebling

      - name: Rename directory
        run: mv static cortexflow-blog

      - name: Deploy to site host
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: ${{ secrets.FTP_SRV }}
          user: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PWD }}
          local_dir: "./cortexflow-blog"
          remote_dir: ${{ secrets.FTP_CF_DIR_2 }}/cortexflow-blog
